/**
 * Type Definitions for Banking Application
 *
 * This file contains TypeScript interfaces that define the data structures
 * used throughout the application. These types ensure type safety and
 * provide clear contracts for data exchange between components and services.
 *
 * For backend integration: These types should match the API response schemas.
 * Consider using tools like OpenAPI/Swagger to generate types from backend specs.
 */

/**
 * User Interface
 * Represents a bank user (customer or admin)
 * - _id: Unique identifier (would be generated by backend database)
 * - name: Full name of the user
 * - email: Email address (used for login)
 * - pass: Password (note: in production, passwords should be hashed)
 * - balance: Current account balance in dollars
 * - branchId: Reference to the user's assigned branch
 * - role: User role for authorization (optional, defaults to customer)
 * - transactions: History of user's banking transactions
 */
export interface User {
  _id: string;
  name: string;
  email: string;
  pass: string; // backend uses `pass` not `password`
  balance: number;
  branchId: string;
  role?: "customer" | "admin";
  transactions?: Transaction[];
}

/**
 * Transaction Interface
 * Represents a single banking transaction
 * - type: Type of transaction (deposit or withdrawal)
 * - amount: Transaction amount in dollars
 * - date: ISO string of when the transaction occurred
 * - branch: Optional branch location where transaction took place
 */
export interface Transaction {
  type: "deposit" | "withdrawal";
  amount: number;
  date?: string;
  branch?: string;
}

/**
 * Branch Interface
 * Represents a bank branch location
 * - _id: Unique identifier for the branch
 * - location: Human-readable location name (e.g., "Downtown Toronto")
 * - cash_limit: Minimum cash requirement the branch must maintain
 * - balance: Current cash balance at the branch
 */
export interface Branch {
  _id: string;
  location: string;
  cash_limit: number;
  balance: number;
}

/**
 * Account Interface
 * Represents a bank account (currently unused but defined for future use)
 * - number: Unique account number
 * - balance: Account balance
 *
 * Note: This interface is not currently used in the app but may be needed
 * for future features like multiple account types or account management.
 */
export interface Account {
  number: string; // unique chequing account number
  balance: number;
}
